project:
  type: website

website:
  title: "OHBM 2025 Educational course"
  sidebar:
    style: "floating"
    search: true
    contents:
      - text: "Introduction"
        href: index.qmd
      - text: "Program"
        href: program.qmd
      - section: "Practical sessions"
        href: timeline.qmd
        contents:
        - spatial_bayes.qmd
        - aribrain_exp.qmd
        - clustertdp.qmd
        - lce_tfce.qmd
        - conf_sets.qmd
      - text: "Speaker overview"
        href: speakers.qmd
    tools: 
      - icon: github
        menu: 
          - text: "Source code"
            href: https://github.com/wdweeda/ohbm2025_educational_course
          - text: "Wouter's Github"
            href: https://github.com/wdweeda/
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
