---
title: "[2a] ARIbrain Explorer"
format:
  html:
    title: ""
type: website
---

## The ARIBrain Explorer: An interactive tool for the analysis of brain activation clusters in fMRI data 

Standard cluster-extent analysis of functional MRI data suffers from the spatial specificity paradox. This paradox states that the larger the cluster that is detected, the less we know about the location of activity within it. This is because a significant cluster means that “there is at least one voxel in this cluster active”, and not “all voxels in this cluster are active”. In essence, once we have detected a cluster, we don’t know exactly how many voxels within that cluster are significant, making localization problematic.

Recently developed methods based on closed testing provide a quantification of the number of truly active voxels within a cluster, called the True Discovery Proportion (TDP). The All-Resolutions Inference framework allows users to calculate the TDP for any cluster in the data without losing family-wise error (FWER) control. In practice, this means that a researcher can freely adjust the size of clusters, intersect clusters with anatomical masks, rerun analysis with a different cluster forming threshold, all with full FWER control. This flexibility requires an interactive implementation that goes beyond what is available in standard analysis packages. In this session we will teach how to use the ARIBrain Explorer software package (Python). For example, we will show users how to find clusters with a minimum TDP and how to interactively increase/decrease the size of each cluster to reach an optimal TDP. In addition, we’ll cover how to properly interpret and convey results.

### Time

Tuesday, Jun 24, 3:10 PM - 3:35 PM

### Speaker

Lucas Peek, PhD <a href='https://www.lucaspeek.com/'><i class="bi bi-globe"></i></a> 

### Materials

- [ARIBrain Explorer](https://github.com/AriBrain/ari-core "ARIBrain Explorer")
