---
title: "[2b] Cluster TDP"
format:
  html:
    title: ""
type: website
---

## ClusterTDP: Cluster Inference via Closed Testing for True Discovery Proportion (TDP) Analysis

In a standard functional MRI data analysis pipeline, the final step often involves a correction of multiple comparisons to determines which regions of the brain show statistically significant activation. The SPM software package supports this by providing users with extensive information on brain activity across different levels of analysis: set (whole brain), cluster (random field-based clusters), and voxelwise statistics. Interpretation of results differs across these levels, as for example cluster-level statistics only tell researchers that there is activity in a cluster, but not how much or where exactly the activation occurs. In other words, cluster-level statistics are about the extent of a cluster, but provide no information of the activity within a cluster. To address this, we recently developed ClusterTDP, which offers a cluster-level compatible measure for the amount of signal within a cluster. This measure estimates the amount of truly activated voxels within a cluster using the true discovery proportion (TDP), thus providing the researcher with valuable information on activity within each cluster. Here we introduce the ClusterTDP SPM extension, which integrates directly into the SPM workflow and reports TDP estimates for each significant cluster. We also provide an companion standalone tool, TDPClusters, which uses herustic algorithms to approximate TDP with potentially higher accuracy. In this session we will show how to install and use both tools, as well as how to interpret results.

### Time

Tuesday, Jun 24, 3:35 PM - 4:00 PM

### Speaker

Xu Chen, PhD <a href='https://www.essex.ac.uk/people/CHENX23803/Xu-Chen'><i class="bi bi-globe"></i></a> 

### Materials

- [ClusterTDP](https://github.com/xuchen312/clusterTDP-SPM "ClusterTDP")

- [TDPClusters](https://github.com/ppgorecki/TDPClusters "TDPClusters")

